### ISSUE TITLE
getaddrinfo tests work on linux but fail in Shadow

### ISSUE THREAD

**Issue by cohosh** [shadow/shadow#1869] opened 2022-01-25 18:58 UTC
**Describe the issue**
After pulling the latest changes for shadow, I built and ran the tests. Two tests fail:

```
99% tests passed, 2 tests failed out of 175

Total Test time (real) =  22.20 sec

The following tests FAILED:
	 86 - getaddrinfo-shadow-ptrace (Failed)
	 87 - getaddrinfo-shadow-preload (Failed)
Errors while running CTest
```

Weirdly, the linux `getaddrinfo` test passes. It's just when it's run in shadow that I have issues:
```
1/175 Test  #87: getaddrinfo-shadow-preload ......................***Failed  Error regular expression found in output. Regex=[main error code '.*' for process]  0.43 sec
  2/175 Test  #86: getaddrinfo-shadow-ptrace .......................***Failed  Error regular expression found in output. Regex=[main error code '.*' for process]  0.45 sec
153/175 Test  #85: getaddrinfo-linux ...............................   Passed    0.01 sec
```

Normally, I'd check for the assertion failure output in `build/Testing/Temporary/LastTest.log` but since these tests are run in shadow, all I get is the shadow log showing the ABRT signal was sent, but since the data directory with the print output from the test is removed, it seems I can't get more details other than the assertion failure. Is there somewhere else I should check?

**To Reproduce**

```
./setup build --clean --test
./setup test
```

**Operating System:**
 - OS and version: Ubuntu 21.10
 - Kernel version: 5.13.0-27-generic # 29-Ubuntu SMP Wed Jan 12 17:36:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Shadow (please complete the following information):**
 - Version: Shadow 2.0.0-pre.4

 - Which plug-ins you are using:  N/A

**Comment by cohosh** [comment] 2022-01-25 20:51
Aha I found it! In `build/src/test/resolver/getaddrinfo-shadow-preload.data/hosts/testnode/`

**Comment by stevenengler** [comment] 2022-01-26 18:46
I'm not able to reproduce this in an Ubuntu 21.10 container. Can you rebuild with the `--debug` option, run `./setup test getaddrinfo`, and add the results from `build/Testing/Temporary/LastTest.log` and `build/src/test/resolver/getaddrinfo-shadow-preload.data/hosts/testnode/testnode.test-getaddrinfo.1000.{stdout,stderr}` here?

**Comment by cohosh** [comment] 2022-01-26 19:19
Yup!
[LastTest.log](https://github.com/shadow/shadow/files/7944574/LastTest.log)
[testnode.test-getaddrinfo.1000.stdout.txt](https://github.com/shadow/shadow/files/7944587/testnode.test-getaddrinfo.1000.stdout.txt)

The .stderr file was empty.

**Comment by cohosh** [comment] 2022-01-26 20:17
BTW, I found this patch useful for debugging tests: https://github.com/cohosh/shadow/commit/763e9428934e9829b7df8338b3dfdc19887e8153

I get the following output from it:
```
# random seed: R02S5e1c7a24e6729287e11b7c75d9b4f720
1..3
# Start of getaddrinfo tests
Expected: EAI_SERVICE(-8) ; Got: EAI_SYSTEM(-11) ; errno: Bad file descriptor
not ok 1 /getaddrinfo/service
Bail out!
```

**Comment by stevenengler** [comment] 2022-01-27 18:52
Thanks! I'm not able to reproduce this in an Ubuntu 21.10 VM either.

Looking through the logs, there are two syscalls that return EBADF.

1. `connect()` --- This seems to be a unix socket, which is created with our rust `socket()` implementation. But we don't yet have a rust `connect()` implementation, so it calls the C `connect()` implementation instead which fails. I see this in the failing logs and in the good logs on my computer, so I don't think this is the issue.
2. `fstat()` --- This is failing with the log message "descriptor -1 out of bounds". I only see `fstat` being called in the failing logs, and not in the good logs on my computer, so this seems more likely to be the issue. But I have no idea why fstat would be called with an fd of -1.

@cohosh Have you ever made changes to how name resolution works on your computer, or changes to `/etc/nsswitch.conf`? Also can you try running the linux test with `strace build/src/test/resolver/test-getaddrinfo` and checking if there are any `fstat()` syscalls made?

**Comment by cohosh** [comment] 2022-01-27 19:17
> Have you ever made changes to how name resolution works on your computer, or changes to `/etc/nsswitch.conf`? 

Not that I know of :)

> Also can you try running the linux test with `strace build/src/test/resolver/test-getaddrinfo` and checking if there are any `fstat()` syscalls made, or anything returning EBADF?

I just ran this and there are none of those for the linux test, looks like it is just happening in the shadow tests. The linux test is passing so I guess that makes sense.

**Comment by cohosh** [comment] 2022-01-27 19:22
I'm going to try a git bisect and see if I can track down when this started failing

**Comment by cohosh** [comment] 2022-01-27 20:21
Okay that wasn't as useful as I'd hoped. It was just this commit: https://github.com/shadow/shadow/commit/dfd75e867912cbffd45b655765fa848ffa0eb1b7

**Comment by sporksmith** [comment] 2022-02-07 20:15
I am surprised this bug doesn't repro for us on ubuntu 21.10. @cohosh btw what version of libc are you using?

I'm getting glibc 2.34 in our docker container:

```
root@47db7d3652b7:~/shadow# ldd build/src/test/resolver/test-getaddrinfo 
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fbb51895000)
       ....

root@47db7d3652b7:~/shadow# dpkg -S /lib/x86_64-linux-gnu/libc.so.6
libc6:amd64: /lib/x86_64-linux-gnu/libc.so.6

root@47db7d3652b7:~/shadow# apt show libc6
Package: libc6
Version: 2.34-0ubuntu3
...
```

**Comment by sporksmith** [comment] 2022-02-07 21:41
@cohosh could you check if https://github.com/shadow/shadow/pull/1893 fixes it? (You'll have some compiler warnings and a failing signal test until https://github.com/shadow/shadow/pull/1892 is merged)

**Comment by cohosh** [comment] 2022-02-08 14:57
Yup seems to work, and just the tests you mentioned are failing:
```
99% tests passed, 2 tests failed out of 180

Total Test time (real) =  30.61 sec

The following tests FAILED:
	 93 - signals-extra-linux (Failed)
	 94 - signals-extra-shadow-preload (Failed)

```

**Closed** 2022-02-08 17:40 UTC
