### ISSUE TITLE
Shadow panics on trying to close tcp socket for exec

### ISSUE THREAD

**Issue by datacompboy** [shadow/shadow#3390] opened 2024-08-14 15:48 UTC
**Describe the issue**
thread 'shadow-worker' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atomic_refcell-0.1.13/src/lib.rs:129:23:
already mutably borrowed

More below

**To Reproduce**
I can't trigger it reproducibly :(

**Operating System (please complete the following information):**
Ubuntu 22.04.4 LTS
5.15.153.1-microsoft-standard-WSL2

**Shadow (please complete the following information):**
Shadow built from 217887cd2fc506b550f10a98786d79e921fb1449 (chdir)
Reproduces with "-g" and without.
Can't share repro setup, unfortunately :(

**Additional context**

The full panic backtrace is below.

The panic is triggered at frame 20 `inetsocket_hasDataToSend` at  src/main/host/descriptor/socket/inet/mod.rs:704:9
when it tries to `socket.borrow().has_data_to_send()`.

The socket comes it seems at frame 60, which, apparently is call for the close on already borrowed ref, no?
```
  60:     0x559ada81733b - shadow_rs::host::descriptor::socket::inet::legacy_tcp::LegacyTcpSocket::close::h108a311beebe05a6
                               at ~/shadow/src/main/host/descriptor/socket/inet/legacy_tcp.rs:229:9
  61:     0x559ada81733b - shadow_rs::host::descriptor::socket::inet::InetSocketRefMut::close::hba7fbbe2b03ffff7
                               at ~/shadow/src/main/utility/enum_passthrough.rs:27:38
```

and the chain of calls is started from frame 71, as part of lambda inside of `Thread::update_for_exec`.

At this point it's beyond my understanding how that supposed to work and what went wrong, but all I know it fails on trying to exec() one binary from another binary. 

*Sigh*.

Any ideas where to look / how to unwind this?

```
thread 'shadow-worker' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atomic_refcell-0.1.13/src/lib.rs:129:23:
already mutably borrowed

stack backtrace:
   0:     0x559ada2d6ba5 - std::backtrace_rs::backtrace::libunwind::trace::h58eed11393533053
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x559ada2d6ba5 - std::backtrace_rs::backtrace::trace_unsynchronized::h6af9bae28ebb6388
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559ada2d6ba5 - std::sys_common::backtrace::_print_fmt::hb6748916642a4fb2
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x559ada2d6ba5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3692694645b1bb6a
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x559ada3250fb - core::fmt::rt::Argument::fmt::h7aa93977ba74ae0f
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/fmt/rt.rs:165:63
   5:     0x559ada3250fb - core::fmt::write::h5131d80b4c69b88d
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/fmt/mod.rs:1168:21
   6:     0x559ada2cc18f - std::io::Write::write_fmt::h1fb327a7d8b0eb36
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/io/mod.rs:1835:15
   7:     0x559ada2d697e - std::sys_common::backtrace::_print::he6ebb7b9d89f4456
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x559ada2d697e - std::sys_common::backtrace::print::h998d75b840f75a73
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x559ada2d93b9 - std::panicking::default_hook::{{closure}}::h18ec7fe6a38b9da0
  10:     0x559ada2d915a - std::panicking::default_hook::hfb3f22c2e4075a6a
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:298:9
  11:     0x559ada48587b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he5de5fef4e7dc8c8
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2077:9
  12:     0x559ada48587b - shadow_rs::core::logger::shadow_logger::init::{{closure}}::hb351528eceb7066d
                               at ~/shadow/src/main/core/logger/shadow_logger.rs:58:9
  13:     0x559ada2d9a7b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb8210adad49183e7
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2077:9
  14:     0x559ada2d9a7b - std::panicking::rust_panic_with_hook::h51af00bcb4660c4e
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:799:13
  15:     0x559ada2d97f4 - std::panicking::begin_panic_handler::{{closure}}::h39f76aa863fbe8ce
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:664:13
  16:     0x559ada2d7069 - std::sys_common::backtrace::__rust_end_short_backtrace::h4d10fc2251b89840
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:171:18
  17:     0x559ada2d9527 - rust_begin_unwind
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
  18:     0x559ada0ffd73 - core::panicking::panic_fmt::h319840fcbcd912ef
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
  19:     0x559ada8155cc - core::panicking::panic_display::he6335aa6667b1a87
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:262:5

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  20:     0x559ada81566e - shadow_rs::host::descriptor::socket::inet::InetSocket::borrow::hc46f458bd02c759c
  21:     0x559ada8137db - inetsocket_hasDataToSend
                               at ~/shadow/src/main/host/descriptor/socket/inet/mod.rs:704:9
  22:     0x559ada600e43 - networkinterface_wantsSend
                               at ~/shadow/src/main/host/network/network_interface.c:347:10
  23:     0x559ada3d3096 - shadow_rs::host::network::interface::NetworkInterface::add_data_source::h4c0783425d8928b9
                               at ~/shadow/src/main/host/network/interface.rs:130:18
  24:     0x559ada3d3096 - shadow_rs::host::host::Host::notify_socket_has_packets::hc5cd4607add3468d
                               at ~/shadow/src/main/host/host.rs:1009:13
  25:     0x559ada55baf3 - shadow_rs::utility::legacy_callback_queue::export::socket_wants_to_send_with_global_cb_queue::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h7747e3c89fa32f9b
                               at ~/shadow/src/main/utility/legacy_callback_queue.rs:120:25
  26:     0x559ada55baf3 - shadow_rs::core::worker::Worker::with_active_host::{{closure}}::{{closure}}::h870353c836f1729f
                               at ~/shadow/src/main/core/worker.rs:114:32
  27:     0x559ada55baf3 - core::option::Option<T>::map::had79a77459fda5aa
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/option.rs:1075:29
  28:     0x559ada55baf3 - shadow_rs::core::worker::Worker::with_active_host::{{closure}}::h539ce53ee7875afd
                               at ~/shadow/src/main/core/worker.rs:114:13
  29:     0x559ada55baf3 - shadow_rs::core::worker::Worker::with::{{closure}}::{{closure}}::h34f8c14eed907dbd
                               at ~/shadow/src/main/core/worker.rs:421:43
  30:     0x559ada55baf3 - core::option::Option<T>::map::h3687ea4a8e6050e6
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/option.rs:1075:29
  31:     0x559ada55baf3 - shadow_rs::core::worker::Worker::with::{{closure}}::hc1f480523a4bd686
                               at ~/shadow/src/main/core/worker.rs:421:27
  32:     0x559ada55baf3 - std::thread::local::LocalKey<T>::try_with::hf0383bffd42b8846
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/local.rs:283:12
  33:     0x559ada55baf3 - shadow_rs::core::worker::Worker::with::h12c2cf29db1c3c2d
                               at ~/shadow/src/main/core/worker.rs:420:9
  34:     0x559ada818f86 - shadow_rs::core::worker::Worker::with_active_host::h5988608b38aa27b0
                               at ~/shadow/src/main/core/worker.rs:112:9
  35:     0x559ada818f86 - shadow_rs::utility::legacy_callback_queue::export::socket_wants_to_send_with_global_cb_queue::{{closure}}::{{closure}}::{{closure}}::h5285f2810e3c41e3
                               at ~/shadow/src/main/utility/legacy_callback_queue.rs:117:21
  36:     0x559ada818f86 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h6d6df159a95a0335
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
  37:     0x559ada5ca2b6 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha19f5029e4802d4e
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2063:9
  38:     0x559ada5ca2b6 - shadow_rs::utility::callback_queue::CallbackQueue::run::h8b4dd56f5e38b642
                               at ~/shadow/src/main/utility/callback_queue.rs:41:13
  39:     0x559ada47f294 - shadow_rs::utility::legacy_callback_queue::with_global_cb_queue::{{closure}}::h0b42b1565718b394
                               at ~/shadow/src/main/utility/legacy_callback_queue.rs:52:13
  40:     0x559ada47f294 - std::thread::local::LocalKey<T>::try_with::ha87b5e44a27a7684
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/local.rs:283:12
  41:     0x559ada47f294 - std::thread::local::LocalKey<T>::with::h4217f63d9d0898ad
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/local.rs:260:9
  42:     0x559ada54c206 - shadow_rs::utility::legacy_callback_queue::with_global_cb_queue::hfa70c92b6b4cd0c6
                               at ~/shadow/src/main/utility/legacy_callback_queue.rs:28:5
  43:     0x559ada54c206 - socket_wants_to_send_with_global_cb_queue
                               at ~/shadow/src/main/utility/legacy_callback_queue.rs:110:9
  44:     0x559ada5ec453 - legacysocket_addToOutputBuffer
                               at ~/shadow/src/main/host/descriptor/socket.c:457:5
  45:     0x559ada5f0314 - _tcp_flush
                               at ~/shadow/src/main/host/descriptor/tcp.c:1354:28
  46:     0x559ada5efd53 - _tcp_sendShutdownFin
                               at ~/shadow/src/main/host/descriptor/tcp.c:1230:9
  47:     0x559ada5f4cbc - _tcp_close
                               at ~/shadow/src/main/host/descriptor/tcp.c:2760:17
  48:     0x559ada5eace6 - _legacysocket_close
                               at ~/shadow/src/main/host/descriptor/socket.c:89:5
  49:     0x559ada5e2d69 - legacyfile_close
                               at ~/shadow/src/main/host/descriptor/descriptor.c:154:5
  50:     0x559ada57aee8 - shadow_rs::host::descriptor::socket::inet::legacy_tcp::LegacyTcpSocket::close::{{closure}}::h0a52d5e68bbb2afe
                               at ~/shadow/src/main/host/descriptor/socket/inet/legacy_tcp.rs:230:22
  51:     0x559ada57aee8 - shadow_rs::core::worker::Worker::with_active_host::{{closure}}::{{closure}}::h7cfe49977bb057c3
                               at ~/shadow/src/main/core/worker.rs:114:32
  52:     0x559ada57aee8 - core::option::Option<T>::map::ha4bae6c8cf49e3df
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/option.rs:1075:29
  53:     0x559ada57aee8 - shadow_rs::core::worker::Worker::with_active_host::{{closure}}::h0b8d67330e2836b6
                               at ~/shadow/src/main/core/worker.rs:114:13
  54:     0x559ada57aee8 - shadow_rs::core::worker::Worker::with::{{closure}}::{{closure}}::he8971a8f721a2369
                               at ~/shadow/src/main/core/worker.rs:421:43
  55:     0x559ada57aee8 - core::option::Option<T>::map::ha862f8ab3cb90a80
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/option.rs:1075:29
  56:     0x559ada57aee8 - shadow_rs::core::worker::Worker::with::{{closure}}::ha597af36d55a73b6
                               at ~/shadow/src/main/core/worker.rs:421:27
  57:     0x559ada57aee8 - std::thread::local::LocalKey<T>::try_with::h22f004b0720e0fb4
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/local.rs:283:12
  58:     0x559ada57aee8 - shadow_rs::core::worker::Worker::with::h8ea35c6244d820d1
                               at ~/shadow/src/main/core/worker.rs:420:9
  59:     0x559ada81733b - shadow_rs::core::worker::Worker::with_active_host::h85d58d1931aa4bd6
                               at ~/shadow/src/main/core/worker.rs:112:9
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  60:     0x559ada81733b - shadow_rs::host::descriptor::socket::inet::legacy_tcp::LegacyTcpSocket::close::h108a311beebe05a6
                               at ~/shadow/src/main/host/descriptor/socket/inet/legacy_tcp.rs:229:9
  61:     0x559ada81733b - shadow_rs::host::descriptor::socket::inet::InetSocketRefMut::close::hba7fbbe2b03ffff7
                               at ~/shadow/src/main/utility/enum_passthrough.rs:27:38
  62:     0x559ada429263 - shadow_rs::host::descriptor::socket::SocketRefMut::close::h4c4dae9d487f23b9
                               at ~/shadow/src/main/utility/enum_passthrough.rs:27:38
  63:     0x559ada429263 - shadow_rs::host::descriptor::FileRefMut::close::h9cd8f8dbbc088e46
                               at ~/shadow/src/main/utility/enum_passthrough.rs:27:38
  64:     0x559ada427619 - shadow_rs::host::descriptor::OpenFileInner::close_helper::h9ed593423994ddea
                               at ~/shadow/src/main/host/descriptor/mod.rs:449:13
  65:     0x559ada427552 - shadow_rs::host::descriptor::OpenFileInner::close::h71e97a9ad9522952
                               at ~/shadow/src/main/host/descriptor/mod.rs:444:9
  66:     0x559ada427552 - shadow_rs::host::descriptor::OpenFile::close::{{closure}}::h136d60528feb3c98
                               at ~/shadow/src/main/host/descriptor/mod.rs:425:44
  67:     0x559ada427552 - core::option::Option<T>::map::h9e9cdb150b542764
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/option.rs:1075:29
  68:     0x559ada427552 - shadow_rs::host::descriptor::OpenFile::close::hd0e087f77b9292fc
                               at ~/shadow/src/main/host/descriptor/mod.rs:425:9
  69:     0x559ada81e67b - shadow_rs::host::descriptor::CompatFile::close::h49c0c86c53240fdf
                               at ~/shadow/src/main/host/descriptor/mod.rs:667:32
  70:     0x559ada81e67b - shadow_rs::host::descriptor::Descriptor::close::h538f77a413e5ed7c
                               at ~/shadow/src/main/host/descriptor/mod.rs:510:9
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  71:     0x559ada81e67b - shadow_rs::host::thread::Thread::update_for_exec::{{closure}}::h8f959bb72453122a
                               at ~/shadow/src/main/host/thread.rs:147:43
  72:     0x559ada81e67b - shadow_rs::utility::callback_queue::CallbackQueue::queue_and_run::hff4d4e153db765a2
                               at ~/shadow/src/main/utility/callback_queue.rs:59:18
  73:     0x559ada3d49eb - shadow_rs::host::thread::Thread::update_for_exec::h262f049c263ad6f1
                               at ~/shadow/src/main/host/thread.rs:144:13
  74:     0x559ada859f84 - shadow_rs::host::process::Process::update_for_exec::h260a1cf08754d1a0
                               at ~/shadow/src/main/host/process.rs:1687:9
  75:     0x559ada48b449 - shadow_rs::host::syscall::handler::unistd::<impl shadow_rs::host::syscall::handler::SyscallHandler>::execve_common::{{closure}}::h5117e993ac2a2361
                               at ~/shadow/src/main/host/syscall/handler/unistd.rs:759:25
  76:     0x559ada3d1e18 - shadow_rs::core::work::task::TaskRef::execute::hf8fad2aca7f566a3
                               at ~/shadow/src/main/core/work/task.rs:32:9
  77:     0x559ada3d1e18 - shadow_rs::host::host::Host::execute::h86d4d95656be9619
                               at ~/shadow/src/main/host/host.rs:859:43
  78:     0x559ada5883a0 - shadow_rs::core::manager::Manager::run::{{closure}}::{{closure}}::{{closure}}::h4fc60140fcc2fa39
                               at ~/shadow/src/main/core/manager.rs:420:37
  79:     0x559ada5883a0 - shadow_rs::core::manager::for_each_host::{{closure}}::{{closure}}::hd29f659289c3341d
                               at ~/shadow/src/main/core/manager.rs:821:13
  80:     0x559ada5883a0 - shadow_rs::core::worker::Worker::with_active_host::{{closure}}::{{closure}}::hbce2722369f89445
                               at ~/shadow/src/main/core/worker.rs:114:32
  81:     0x559ada5883a0 - core::option::Option<T>::map::hcb455a2034fcb333
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/option.rs:1075:29
  82:     0x559ada5883a0 - shadow_rs::core::worker::Worker::with_active_host::{{closure}}::hbaccec08ca57e267
                               at ~/shadow/src/main/core/worker.rs:114:13
  83:     0x559ada5883a0 - shadow_rs::core::worker::Worker::with::{{closure}}::{{closure}}::h2257330c32612b9b
                               at ~/shadow/src/main/core/worker.rs:421:43
  84:     0x559ada5883a0 - core::option::Option<T>::map::hccdb2e8f4b6d5980
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/option.rs:1075:29
  85:     0x559ada5883a0 - shadow_rs::core::worker::Worker::with::{{closure}}::hc169cae3c5fac60a
                               at ~/shadow/src/main/core/worker.rs:421:27
  86:     0x559ada5883a0 - std::thread::local::LocalKey<T>::try_with::h747f13851e2b0029
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/local.rs:283:12
  87:     0x559ada5883a0 - shadow_rs::core::worker::Worker::with::hbd23fd10f1a1a09e
                               at ~/shadow/src/main/core/worker.rs:420:9
  88:     0x559ada83b126 - shadow_rs::core::worker::Worker::with_active_host::hf98e18a678827b55
                               at ~/shadow/src/main/core/worker.rs:112:9
  89:     0x559ada83b126 - shadow_rs::core::manager::for_each_host::{{closure}}::hdca696fb330c525d
                               at ~/shadow/src/main/core/manager.rs:820:9
  90:     0x559ada83b126 - scheduler::thread_per_core::HostIter<HostType>::for_each::h91d44e3994b029f5
                               at ~/shadow/src/lib/scheduler/src/thread_per_core.rs:208:43
  91:     0x559ada54aa5a - scheduler::HostIter<HostType>::for_each::h5aaff16d699f6885
                               at ~/shadow/src/lib/scheduler/src/lib.rs:249:39
  92:     0x559ada54aa5a - shadow_rs::core::manager::for_each_host::h7439722b09a2cd03
                               at ~/shadow/src/main/core/manager.rs:818:5
  93:     0x559ada54aa5a - shadow_rs::core::manager::Manager::run::{{closure}}::{{closure}}::hd529df66da86422d
                               at ~/shadow/src/main/core/manager.rs:417:29
  94:     0x559ada54aa5a - scheduler::SchedulerScope<HostType>::run_with_data::{{closure}}::h4f5b283ea4260551
                               at ~/shadow/src/lib/scheduler/src/lib.rs:226:17
  95:     0x559ada54aa5a - scheduler::thread_per_core::SchedulerScope<HostType>::run_with_data::{{closure}}::h266c820adf222255
                               at ~/shadow/src/lib/scheduler/src/thread_per_core.rs:174:13
  96:     0x559ada6ac585 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h0c12acdb5341415b
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2077:9
  97:     0x559ada6ac585 - scheduler::pools::unbounded::work_loop::h506ca6950663079b
                               at ~/shadow/src/lib/scheduler/src/pools/unbounded.rs:269:31
  98:     0x559ada6b6bab - scheduler::pools::unbounded::UnboundedThreadPool::new::{{closure}}::h6542c28cb4ae28f9
                               at ~/shadow/src/lib/scheduler/src/pools/unbounded.rs:71:21
  99:     0x559ada6b6bab - std::sys_common::backtrace::__rust_begin_short_backtrace::hf95ff3cf3adf708f
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:155:18
 100:     0x559ada6aee0a - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::ha92c275f8f93605c
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/mod.rs:542:17
 101:     0x559ada6aee0a - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd24821f73559ef46
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panic/unwind_safe.rs:272:9
 102:     0x559ada6aee0a - std::panicking::try::do_call::h2c30874af3e5ce48
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:559:40
 103:     0x559ada6aee0a - std::panicking::try::h23881c52df4bb0cd
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:523:19
 104:     0x559ada6aee0a - std::panic::catch_unwind::h2f366fb2064d1650
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panic.rs:149:14
 105:     0x559ada6aee0a - std::thread::Builder::spawn_unchecked_::{{closure}}::h323c95745ff7925b
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/mod.rs:541:30
 106:     0x559ada6aee0a - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1bb090ea3faa2a11
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
 107:     0x559ada2e3a1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3af90da315d4b185
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2063:9
 108:     0x559ada2e3a1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4e7f3b3405b4b88b
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2063:9
 109:     0x559ada2e3a1b - std::sys::pal::unix::thread::Thread::new::thread_start::h3b8e81128811868f
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys/pal/unix/thread.rs:108:17
 110:     0x7f49bd1b8ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
 111:     0x7f49bd24a850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
 112:                0x0 - <unknown>
```

**Comment by datacompboy** [comment] 2024-08-14 17:41
Extra info...
Last words before crash is:
```
00:00:25.248210 [246705:shadow-worker] 00:12:40.103231530 [DEBUG] [host] [mod.rs:710] [shadow_rs::host::syscall::handler] Handled 59 syscalls
00:00:25.248215 [246705:shadow-worker] 00:12:40.103231530 [DEBUG] [host] [mod.rs:714] [shadow_rs::host::syscall::handler] Thread 1221 syscall counts: {rt_sigaction:55, dup3:3, execve:1, rt_sigprocmask:1}
```

and strace for this thread is quite innocent:
```
00:12:40.103156480 [tid 1009] openat(-100, "/dev/null", O_CLOEXEC, Mode(0x0)) = 17
  (future stdin)
00:12:40.103157530 [tid 1009] epoll_ctl(4, 1, 17, 0xc0003c6eb4) = -1 (EPERM)
00:12:40.103157530 [tid 1009] pipe2([0, 0] (0xc0003c6f40), O_CLOEXEC) = 0
  (here it get pipe fds 18 and 19, future stdout/stderr)
00:12:40.103159530 [tid 1009] epoll_ctl(4, 1, 18, 0xc0003c6eb4) = 0
00:12:40.103159530 [tid 1009] fcntl(18, 3) = 0
00:12:40.103161530 [tid 1009] fcntl(18, 4) = 0
00:12:40.103161530 [tid 1009] epoll_ctl(4, 1, 19, 0xc0003c6eb4) = 0
00:12:40.103163530 [tid 1009] fcntl(19, 3) = 1
00:12:40.103163530 [tid 1009] fcntl(19, 4) = 0
00:12:40.103165530 [tid 1009] fcntl(19, 3) = 2049
00:12:40.103165530 [tid 1009] fcntl(19, 4) = 0
00:12:40.103167530 [tid 1009] fcntl(19, 3) = 1
00:12:40.103167530 [tid 1009] fcntl(19, 4) = 0
00:12:40.103169530 [tid 1009] pipe2([0, 0] (0xc0003c6df8), O_CLOEXEC) = 0
  (here it get pipe fds 20 & 21)
00:12:40.103171530 [tid 1009] rt_sigprocmask(2, 0x0, 0xc0003aa480, 8) = 0
00:12:40.103171530 [tid 1009] rt_sigprocmask(2, 0x555556882988, 0x0, 8) = 0
00:12:40.103173530 [tid 1009] clone(CloneFlags(CLONE_VM | CLONE_VFORK | 0x11), 0x0, 0x0 <null>, 0x0 <null>, 0x0) = 1221

then 1009 does:
  00:12:40.103175530 [tid 1009] close(21) = 0
  00:12:40.103175530 [tid 1009] read(20, 0xc0003c6e80, 8) = <blocked>

and 1221 does:
00:12:40.103173530 [tid 1221] rt_sigaction(1, 0xc0003c6a70, 0x0, 8) = 0
00:12:40.103173530 [tid 1221] rt_sigaction(2, 0xc0003c6a70, 0x0, 8) = 0
  ...
00:12:40.103227530 [tid 1221] rt_sigaction(64, 0xc0003c6a70, 0x0, 8) = 0
00:12:40.103227530 [tid 1221] rt_sigprocmask(2, 0xc0003c6ae8, 0x0, 8) = 0
00:12:40.103229530 [tid 1221] dup3(17, 0, (empty)) = 0
00:12:40.103229530 [tid 1221] dup3(19, 1, (empty)) = 1
00:12:40.103229870 [tid 1011] epoll_pwait(4, 0x7fffc77fd200, 128, 499, 0x0, 140736540431392) = <blocked>
  ^^ ther ealso 1011 doing something around the same time
00:12:40.103231530 [tid 1221] dup3(19, 2, (empty)) = 2
00:12:40.103231530 [tid 1221] execve("bin/binbin", 0xc001e8ffa0, 0xc0006fbad0) = <blocked>
  ^^ the last entry, the BOOM
```

**Comment by stevenengler** [comment] 2024-08-16 02:54
Thanks for the bug report and the stack trace! So the issue is that some TCP sockets are marked CLOEXEC, and so when exec() is called, shadow closes the sockets. Our TCP sockets are still written in C, so they have an ugly workaround for emitting events. For C compatability we should have been initializing a global callback queue to avoid double borrows, but it wasn't added to `Thread::update_for_exec`.

#3391 should fix it.

**Comment by stevenengler** [comment] 2024-08-16 17:30
I'm closing this since it should be fixed, but I don't have an example I can test to make sure.

If this isn't fixed, please reopen it.

**Closed** 2024-08-16 17:30 UTC

**Comment by datacompboy** [comment] 2024-08-19 15:48
Thank you very much! Can confirm: #3391 indeed fixed the issue :)
