### ISSUE TITLE
some idea about libevent2 deferred callbacks

### ISSUE THREAD

**Issue by vladie** [shadow/shadow#252] opened 2015-01-21 16:06 UTC
yesterday i've tried to make simple ping application, which sends tcp-pings every 5 seconds. once i've finished code writing, i've realised that shadow didn't support libevent deferred callbacks (which i create using event_new + event_add). i've studied shadow-tor-plugin and discovered that tor plugin makes per-second calls of tor functions by itself, libevent events not used (because they will work only with event_base_dispatch() endless loop). my idea for solving this problem is to hook event_add:

```
static void _event_executeCallbackInPluginContext(gpointer data, ShadowPluginCallbackFunc callback)
{
   callback(NULL);
}

int event_add(struct event *ev, const struct timeval *tv)
{
   int result;

   ENSURE(libc, "", event_add);

   if (shouldForwardToLibC())
   {
      return director.libc.event_add(ev, tv);
   }

   Host *node = _interposer_switchInShadowContext();
   if ( tv )
   {
      Thread *thread = worker_getActiveThread();
      if (thread)
      {
         struct _Process *proc = thread_getParentProcess(thread);
        process_callback(proc, (CallbackFunc)_event_executeCallbackInPluginContext, NULL, process_getNotifyFunc(proc), (tv->tv_sec * (uint64_t)1000) + (tv->tv_usec / 1000));
      }
   }
   _interposer_switchOutShadowContext(node);

   result = director.libc.event_add(ev, tv);
   return result;
}
```

in this case, deferred callback will call plugin notify function, which will call event_base_loop(..., EVLOOP_NONBLOCK), which will process event, which was placed in queue by calling original libevent's event_add. this hack works for my sample, but i didn't studied shadow architecture completely yet.

**Comment by robgjansen** [comment] 2015-01-21 18:21
I have already created issue #183 to add support for libevent timer events. To be clear, non-timeout events like reading and writing work properly, only timer events are problematic.

Although your solution would work, I prefer that library support is handled on the plug-in side of things to keep Shadow as minimal and lean as possible. Please see #183 for my suggestion of how to handle timer events, and let me know if you have any thoughts there.

**Comment by robgjansen** [comment] 2015-01-21 18:22
I am marking this as a duplicate of #183.

**Closed** 2015-01-21 18:22 UTC
Labels: wontfix
