### ISSUE TITLE
Problems using local LLVM installs

### ISSUE THREAD

**Issue by jdgeddes** [shadow/shadow#298] opened 2015-09-29 02:28 UTC
I'm not sure if this is an issue with shadow or LLVM, but there were issues using a local LLVM install.  It seemed cmake wouldn't actually find the directory for LLVM includes or library, so LLVM_INCLUDE_DIRS and LLVM_LIBRARY_DIRS wouldn't be set.  This isn't an issue if the files are in the standard directories (e.g /usr/include) but otherwise cmake cannot find the include files during compilation.

In the `llvm/cmake/` directory there is an LLVM-Config and LLVMConfig file.  They seem to be fairly different, and only in LLVMConfig do the `LLVM_INCLUDE_DIRS` and `LLVM_LIBRARY_DIRS` variables get set.  However, in the AddLLVM.cmake file there is only `include(LLVM-Config)`.  I was able to fix the problem by adding the line `include(LLVMConfig)` to AddLLVM.cmake, so I'm not sure if this is an issue with LLVM or if one of the shadow cmake files needs to be changed.  This was all with LLVM v3.2.

**Comment by robgjansen** [comment] 2015-09-29 20:23
The latest LLVM as of now is version 3.7. It seems like LLVM changed the recommended build process as of 3.5.
http://llvm.org/docs/CMake.html#embedding-llvm-in-your-project

I've been using 3.5 for a while, but have not recently tried using a non-OS installed version.

**Comment by robgjansen** [comment] 2016-02-20 04:03
FYI, I just tried local installs of LLVM versions 3.5.2, 3.6.2, 3.7.0, and 3.7.1 as I was fixing #301 and I was not able to reproduce the `LLVMConfig` vs `LLVM-Config` problem.

**Comment by robgjansen** [comment] 2016-02-20 04:08
I'm closing this since I can't reproduce it on local installs of recent versions of LLVM. Please re-open if you still have this issue.

**Closed by robgjansen** 2016-02-20 04:08 UTC
Labels: bug, shadow-core
