### ISSUE TITLE
Help me with ./setup build

### ISSUE THREAD

**Issue by zambo92** [shadow/shadow#670] opened 2019-01-09 15:16 UTC
When I launch the command "sudo ./setup build --clean --debug --test" this error is shown: why?

> Scanning dependencies of target vdlconfig
> [  3%] Generating vdl-config.h
> src/external/elf-loader/CMakeFiles/vdlconfig.dir/build.make:60: recipe for target 'src/external/elf-loader/vdl-config.h' failed
> make[2]: *** [src/external/elf-loader/vdl-config.h] Error 1
> make[2]: *** Eliminazione del file "src/external/elf-loader/vdl-config.h"
> CMakeFiles/Makefile2:646: recipe for target 'src/external/elf-loader/CMakeFiles/vdlconfig.dir/all' failed
> make[1]: *** [src/external/elf-loader/CMakeFiles/vdlconfig.dir/all] Error 2
> Makefile:162: recipe for target 'all' failed
> make: *** [all] Error 2
> 2019-01-09 16:06:29,239 [ERROR] Non-zero return code from make.

I have all the required packages.
What am I doing wrong?
Thank you so much.

**Comment by jtracey** [comment] 2019-01-09 20:20
You installed the glibc debug files?
Which distro and version are you using?
If you want to see the specific error message, you can run the `src/external/elf-loader/extract-system-config.py` script yourself.

**Comment by zambo92** [comment] 2019-01-10 11:04
> You installed the glibc debug files?
I think it is installed by "sudo apt-get install libc-dbg", right?

> Which distro and version are you using?
I am using Ubuntu 18.04.1 LTS.

> If you want to see the specific error message, you can run the src/external/elf-loader/extract-system-config.py script yourself.
If I run the python file with './extract-system-config.py' nothing happens...It's correct?
Sorry for the question but I'm not expert in this field.
I'm doing a master thesis concerning Tor and  I need to use Shadow for some tests.
I don't understand what the problem is :(

**Comment by jtracey** [comment] 2019-01-11 03:16
> I think it is installed by "sudo apt-get install libc-dbg", right?

Yes, that's the right package.

> I am using Ubuntu 18.04.1 LTS.

This is the main development environment I use, so it should work.

> If I run the python file with './extract-system-config.py' nothing happens...It's correct?

No, that should print information from the debug symbols installed in your system. This is a normal, x86-64 computer, right?
What is the output of `ls /usr/lib/debug/lib/x86_64-linux-gnu/ld-*` on this machine?

**Comment by zambo92** [comment] 2019-01-11 17:19
> What is the output of ls /usr/lib/debug/lib/x86_64-linux-gnu/ld-* on this machine?

/usr/lib/debug/lib/x86_64-linux-gnu/ld-2.27.so

**Comment by jtracey** [comment] 2019-01-11 20:15
Do you know how to write python? If that file exists at that location ("ld-2.27.so"), then `extract-system-config.py` should be printing some information. Since I have the same setup and can't reproduce, I'm not sure how to figure out the problem. If I were you, I would start with printing some extra information around here:
https://github.com/shadow/shadow/blob/ce52ebe0a988dfeb034c50f53355567591d4b936/src/external/elf-loader/extract-system-config.py#L239
since right after that call is when the first thing is printed.

**Comment by zambo92** [comment] 2019-01-13 00:04
Thank you for the suggestion. In the next days I will do some tests and then I will let you know the results :)
If someone else had the same problem and found the cause, let us know ;)

**Comment by Stefanoga** [comment] 2019-01-25 10:34
I have the same problem. Is there anyone who knows how i can do to use shadow? It is necessary for my graduate thesis

**Comment by Reyhanea** [comment] 2019-01-25 14:45
I had the same problem. The Ubuntu version which I used was 14.04.
 According to the provided points in 
https://github.com/shadow/shadow/wiki/1.1-Shadow,
if the version of your Ubuntu is 14.04 or between 14.04 and 16.04, libigraph0v5  should be replaced with libigraph0 in the installing processes. 
However, with Ubuntu 16.04, Shadow will be installed easily without any problem for me. I suggest you install Shadow in Ubuntu with 16.04 or other higher versions.

**Comment by Stefanoga** [comment] 2019-01-25 15:09
I am using Ubuntu 18.10 but the problem still persist

**Comment by robgjansen** [comment] 2019-01-25 15:37
OK, so the problem reportedly occurs on Ubuntu versions `18.04.1 LTS` and `18.10`.

I just set up a fresh VM of `18.04.1 LTS`, and executed the following commands exactly as specified on the wiki:

```
sudo apt-get install -y gcc g++ python libglib2.0-0 libglib2.0-dev libigraph0v5 libigraph0-dev cmake make xz-utils
sudo apt-get install libc-dbg
sudo apt-get install -y python-matplotlib python-numpy python-scipy python-networkx python-lxml
sudo apt-get install -y git dstat screen htop
git clone https://github.com/shadow/shadow.git
cd shadow
./setup build --clean --debug --test
```

The build process prints the following warnings:

```
[ 20%] Building C object src/main/CMakeFiles/shadow.dir/core/shd-main.c.o
/home/rjansen/shadow/src/main/core/shd-main.c: In function ‘_main_computeLoadSize’:
/home/rjansen/shadow/src/main/core/shd-main.c:100:14: warning: null argument where non-null required (argument 1) [-Wnonnull]
     result = dlinfo(NULL, RTLD_DI_STATIC_TLS_SIZE, &tlsSizeStart);
              ^~~~~~
/home/rjansen/shadow/src/main/core/shd-main.c:132:14: warning: null argument where non-null required (argument 1) [-Wnonnull]
     result = dlinfo(NULL, RTLD_DI_STATIC_TLS_SIZE, &tlsSizeEnd);
              ^~~~~~

Scanning dependencies of target shadow-interpose
[ 30%] Building C object src/preload/CMakeFiles/shadow-interpose.dir/shd-interposer.c.o
In file included from /home/rjansen/shadow/src/preload/shd-interposer.c:222:0:
/usr/include/pthread.h: In function ‘__pthread_unwind_next’:
/home/rjansen/shadow/src/preload/shd-preload-defs.h:271:1: warning: ‘noreturn’ function does return
 PRELOADDEF(      , void, __pthread_unwind_next, (__pthread_unwind_buf_t *a), a);
 ^~~~~~~~~~
/usr/include/stdlib.h: In function ‘exit’:
/home/rjansen/shadow/src/preload/shd-interposer.c:417:1: warning: ‘noreturn’ function does return
 }
 ^
/usr/include/pthread.h: In function ‘pthread_exit’:
/home/rjansen/shadow/src/preload/shd-interposer.c:427:1: warning: ‘noreturn’ function does return
 }
 ^
/usr/include/stdlib.h: In function ‘abort’:
/home/rjansen/shadow/src/preload/shd-interposer.c:437:1: warning: ‘noreturn’ function does return
 }
 ^

[ 50%] Building C object src/external/elf-loader/test/CMakeFiles/test13.dir/test13.c.o
[ 50%] Linking C executable test13
libf.so: warning: undefined reference to `call_function_l'

[ 61%] Building C object src/external/elf-loader/test/CMakeFiles/test0.dir/test0.c.o
[ 61%] Linking C executable test0
libf.so: warning: undefined reference to `call_function_l'

[ 62%] Building C object src/external/elf-loader/test/CMakeFiles/test0_1.dir/test0_1.c.o
[ 63%] Linking C executable test0_1
libf.so: warning: undefined reference to `call_function_l'
```

Which we can safely ignore and should actually suppress because these are all safe issues.

Then the following proceed correctly with no failed tests:

```
./setup install
./setup test
```

Then I looked back at the OP and saw this:

> When I launch the command "sudo ./setup build --clean --debug --test" this error is shown: why?

I noticed the command they ran was `sudo ./setup build --clean --debug --test`, meaning they ran it with admin privileges. I'm not sure why, because Shadow does not require root privileges and none of the instructions state that Shadow should be installed with root or sudo.

Nevertheless, I tried it anyway:

```
cd ..
rm -rf ~/.shadow
git clone https://github.com/shadow/shadow.git shadow-with-sudo-bad-idea
cd shadow-with-sudo-bad-idea
sudo ./setup build --clean --debug --test
```

and that also compiled correctly with no build errors.

I then ran the python script and got the following output

```
$ python src/external/elf-loader/extract-system-config.py
#define CONFIG_RTLD_GLOBAL_SIZE 3960
#define CONFIG_RTLD_GLOBAL_RO_SIZE 440
#define CONFIG_RTLD_DL_PAGESIZE_OFFSET 24
#define CONFIG_RTLD_DL_CLKTCK_OFFSET 56
#define CONFIG_TCB_SIZE 2304
#define CONFIG_TCB_TCB_OFFSET 0
#define CONFIG_TCB_DTV_OFFSET 8
#define CONFIG_TCB_SELF_OFFSET 16
#define CONFIG_TCB_SYSINFO_OFFSET 32
#define CONFIG_TCB_STACK_GUARD 40
#define CONFIG_SYSTEM_LDSO_LIBRARY_PATH "/usr/local/lib:/var/lib/VBoxGuestAdditions/lib:/usr/local/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/libfakeroot:"
```

I can't imagine what is going on here. I recommend to reinstall the development packages and try building Shadow again **without** using sudo.

```
sudo apt-get install --reinstall -y gcc g++ python libglib2.0-0 libglib2.0-dev libigraph0v5 libigraph0-dev cmake make xz-utils
sudo apt-get install --reinstall libc-dbg
sudo apt-get install --reinstall -y python-matplotlib python-numpy python-scipy python-networkx python-lxml
sudo apt-get install --reinstall -y git dstat screen htop
```

Otherwise, please help us debug by adding some print statements to the `shadow/src/external/elf-loader/extract-system-config.py` so we can get some additional context information.

**Comment by beastsam** [comment] 2019-02-20 03:40
hi, I met the same questions just like zambo92, my system is CentOS Linux release 7.5.1804(core), when i run the `./(or python) src/external/elf-loader/extract-system-config.py` ,nothing script. And the path /usr/lib/debug/lib/x86_64-linux-gnu is not exist on my computer, i mean my path is just /usr/lib/debug/lib, i don't find /x86_64-linux-gnu. 
The problem is just the system version? Is there someone who solved the problem without change the system?
@zambo92 @jtracey

**Comment by ZWZfriso** [comment] 2019-02-22 04:21
Is there someone had the same problem and solved it?
I meet the same problem and my environment is Ubuntu version 18.04.2 LTS

**Comment by jtracey** [comment] 2019-02-22 20:38
Again, if anyone wants help with this issue, you're going to have to give more information. Shadow works on fresh Ubuntu 18.04 installs that follow the instructions, and I haven't been able to reproduce this issue, so you need to modify the extract-system-config.py script to print more to see why it's not working.

**Comment by zambo92** [comment] 2019-02-25 00:05
> hi, I met the same questions just like zambo92, my system is CentOS Linux release 7.5.1804(core), when i run the `./(or python) src/external/elf-loader/extract-system-config.py` ,nothing script. And the path /usr/lib/debug/lib/x86_64-linux-gnu is not exist on my computer, i mean my path is just /usr/lib/debug/lib, i don't find /x86_64-linux-gnu.
> The problem is just the system version? Is there someone who solved the problem without change the system?
> @zambo92 @jtracey

As far as I'm concerned, I probably had some corrupt packages since I had no problems with the system re-initialization.

**Comment by ZWZfriso** [comment] 2019-02-25 02:46
Here are my change in 

> ./src/external/elf-loader/extract-system-config.py: (line 239)
>      print 'str(debug_filename):',str(debug_filename)
>     debug = DebugData (debug_filename)
>     data = debug.get_struct_size ('rtld_global')
>     print 'str(data):',str(data)
> 
>  if data is None:
>         sys.exit (1)
>     config.write ('#define CONFIG_RTLD_GLOBAL_SIZE ' + str(data.data) + '\n')

Here are the print out:
> Scanning dependencies of target vdlconfig
> [  2%] Generating vdl-config.h
> str(debug_filename): /usr/lib/debug/lib/x86_64-linux-gnu/ld-2.27.so
> str(data): None
> src/external/elf-loader/CMakeFiles/vdlconfig.dir/build.make:60: recipe for target 'src/external/elf-loader/vdl-config.h' failed

The data is None and thus go to the sys.exit.
What's wrong with it? Is there something wrong with my Ubuntu environment?

**Comment by jtracey** [comment] 2019-02-26 04:35
I just realized we have an unstated dependency of readelf (in the elfutils package in Debian/Ubuntu). It could be that this used to be a dependency of something we installed, like gcc, but no longer is.

@ZWZfriso Can you check that the `elfutils` package is installed? If it's not, then that's the problem. If it is, can you post the output of:
 `readelf -wi /usr/lib/debug/lib/x86_64-linux-gnu/ld-2.27.so | grep -C 10 -m 1 rtld_global`

**Comment by ZWZfriso** [comment] 2019-02-26 06:43
My elfutils maybe dosen't install:
> friso@friso-Vostro-3668:~$ sudo apt-get -y install elfutils
then it install  `elfutils libasm1` 

But after I have already installed it, I `sudo ./setup build --clean --debug --test` the same error still. 

Here are the print out after I have installed elfutils:
> friso@friso-Vostro-3668:~$ readelf -wi /usr/lib/debug/lib/x86_64-linux-gnu/ld-2.27.so | grep -C 10 -m 1 rtld_global
>     <3543>   DW_AT_data_member_location: 8
>  <2><3544>：缩写编号：0
>  <1><3545>：缩写编号：9 (DW_TAG_array_type)
>     <3546>   DW_AT_type        : <0xda>
>     <354a>   DW_AT_sibling     : <0x3555>
>  <2><354e>：缩写编号：10 (DW_TAG_subrange_type)
>     <354f>   DW_AT_type        : <0x78>
>     <3553>   DW_AT_upper_bound : 49
>  <2><3554>：缩写编号：0
>  <1><3555>：缩写编号：95 (DW_TAG_structure_type)
>     <3556>   DW_AT_name        : (indirect string, offset: 0x171c): rtld_global
>     <355a>   DW_AT_byte_size   : 3960
>     <355c>   DW_AT_decl_file   : 55
>     <355d>   DW_AT_decl_line   : 285
>     <355f>   DW_AT_sibling     : <0x36f9>
>  <2><3563>：缩写编号：5 (DW_TAG_member)
>     <3564>   DW_AT_name        : (indirect string, offset: 0x1134): _dl_ns
>     <3568>   DW_AT_decl_file   : 55
>     <3569>   DW_AT_decl_line   : 326
>     <356b>   DW_AT_type        : <0x36f9>
>     <356f>   DW_AT_data_member_location: 0
>

**Comment by jtracey** [comment] 2019-02-27 23:19
@ZWZfriso Thank you! I'm now able to reproduce, the issue is the regex don't work with different language settings. I'll fix it, but until then, you should be able to fix it with a `LANGUAGE=C` or `LANGUAGE=en_US` environment variable. E.g.,

`LANGUAGE=C ./setup build -c -t && ./setup install`

(You should **not** be building as root/sudo, you might need to delete some build files as root if you tried to before).

**Comment by jtracey** [comment] 2019-02-28 00:52
@robgjansen Finally looking at how the `extract-system-config.py` really works (we've just been patching it since we inherited it), it looks really brittle to me. It's been calling `readelf`, which I'm not sure how we've been getting away without having `elfutils` as a dependency (`apt-cache rdepends elfutils` on Ubuntu doesn't show anything obviously leading to something listed in the wiki). Aside from this language issue, I don't think readelf claims to have a stable output for parsing, and some rare systems opt to use alternatives (e.g., objdump) instead of shipping it at all. I haven't tried it yet, but I'm thinking of using [pyelftools](https://github.com/eliben/pyelftools) to read the ELF debug file (i.e. the DWARF file) instead. It's available via pip, and also has packages in Debian and Ubuntu's apt repos (I haven't checked any other distros). Would you be okay with adding that as a dependency? The next best alternative would be just implementing DWARF parsing myself, which I'm guessing wouldn't be *too* hard since we're just reading a few basic fields, but I'd rather just use the library since this is the exact sort of problem it solves.

**Comment by ZWZfriso** [comment] 2019-02-28 02:46
> @ZWZfriso Thank you! I'm now able to reproduce, the issue is the regex don't work with different language settings. I'll fix it, but until then, you should be able to fix it with a `LANGUAGE=C` or `LANGUAGE=en_US` environment variable. E.g.,
> 
> `LANGUAGE=C ./setup build -c -t && ./setup install`
> 
> (You should **not** be building as root/sudo, you might need to delete some build files as root if you tried to before).

I use `LANGUAGE=en_US  ./setup build -c -t` can build successfully, but the `./setup install` can't success because it needs administrative privileges. So the `sudo` is essential in install command.

So crazy I can success, since that my mentor says it is a difficult project! Thank you for your help and hope everyone coming here will build successfully!

**Comment by robgjansen** [comment] 2019-02-28 13:54
> I use LANGUAGE=en_US ./setup build -c -t can build successfully, but the ./setup install can't success because it needs administrative privileges. So the sudo is essential in install command.

@ZWZfriso the only reason it needs admin privileges is because you executed the build command with sudo when you first ran the setup script. So some of the build files were created with the incorrect permissions. I **strongly** recommend that you restart the build as follows, otherwise you may run into other permissions issues in the future:

```
sudo rm -rf build
LANGUAGE=C ./setup build -c -t
./setup install
```

I think the above should help everyone who is observing the setup script failing due to a failure to correctly parse non-english characters.

> Would you be okay with adding \[pyelftools\] as a dependency?

Yes, this totally makes sense. I created #679 from your comment; let's track it there.

**Closed by robgjansen** 2019-02-28 13:54 UTC
