### ISSUE TITLE
setup test fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by sakib570** [shadow/shadow#755] opened 2020-04-08 11:00 UTC
Hi,

I am trying to install shadow on Ubuntu 18.04 and it is failing in setup test step. Here in the snapshot of the error.

Total Test time (real) =  81.43 sec

The following tests FAILED:
		 4 - dynlink-shadow (SEGFAULT)
		25 - determinism1a-shadow (SEGFAULT)
		26 - determinism1b-shadow (SEGFAULT)
		28 - determinism2a-shadow (SEGFAULT)
		29 - determinism2b-shadow (SEGFAULT)
		33 - epoll-writeable-shadow (SEGFAULT)
		36 - phold-shadow (SEGFAULT)
		37 - phold-threaded-shadow (SEGFAULT)
		45 - shutdown-shadow (SEGFAULT)
		51 - sockbuf-shadow (SEGFAULT)
		53 - tcp-blocking-loopback-shadow (SEGFAULT)
		54 - tcp-blocking-lossless-shadow (SEGFAULT)
		55 - tcp-blocking-lossy-shadow (SEGFAULT)
		57 - tcp-nonblocking-poll-loopback-shadow (SEGFAULT)
		58 - tcp-nonblocking-poll-lossless-shadow (SEGFAULT)
		59 - tcp-nonblocking-poll-lossy-shadow (SEGFAULT)
		61 - tcp-nonblocking-epoll-loopback-shadow (SEGFAULT)
		62 - tcp-nonblocking-epoll-lossless-shadow (SEGFAULT)
		63 - tcp-nonblocking-epoll-lossy-shadow (SEGFAULT)
		65 - tcp-nonblocking-select-loopback-shadow (SEGFAULT)
		66 - tcp-nonblocking-select-lossless-shadow (SEGFAULT)
		67 - tcp-nonblocking-select-lossy-shadow (SEGFAULT)
		69 - tcp-iov-shadow (SEGFAULT)
		71 - timerfd-shadow (SEGFAULT)
Errors while running CTest
2020-04-08 12:53:09,580 [INFO] ctest -j4 returned 8
2020-04-08 12:53:09,580 [WARNING] Failed to pass all test cases!

Any suggestions? I mostly checked the dependencies and it seems fine.

**Comment by robgjansen** [comment] 2020-04-08 15:49
Our continuous integration scripts target Ubuntu 18.04 as well and those are passing. Normally when so many tests fails, it has something to do with the install/setup procedure. Did you run the tests like this:

```bash
./setup build -ct
./setup install
./setup test
```

If the above fails, you'll need to provide us more information. So far all we know is that tests are failing and that doesn't help us provide you with very much useful feedback. For example, posting the full output from the `./setup build -ct` step might help. You could also fill out the bug report form:

---

**Describe the issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior. If you problem involves a simulation, please include the configuration file that you used.

**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
[e.g., CentOS Linux release 7.6.1810 (Core)]
 - Kernel version: post the output of `uname -a`  
[e.g. Linux sol 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux]

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
[e.g. Shadow v1.13.0-36-g337d565-dirty 2019-02-07 (built 2019-02-08) running GLib v2.54.2 and IGraph v0.7.1]
 - Which plug-ins you are using:  
[e.g. Shadow-Tor]

**Additional context**
Add any other context about the problem here.

**Comment by sakib570** [comment] 2020-04-21 16:31
Hi, thanks a lot for your feedback. I followed the steps as you mentioned in the comments. It seems that build and installation can complete successfully only the test is failing for some reason. I am attaching build, installation and test logs for your reference. The test log file is in zip format as I needed to compress it due to size issues.

Let me know if you find some insights regarding the issue. Thanks a lot for your help. I really appreciate your prompt response.

[build.log](https://github.com/shadow/shadow/files/4511245/build.log)
[install.log](https://github.com/shadow/shadow/files/4511247/install.log)
[test.zip](https://github.com/shadow/shadow/files/4511264/test.zip)

**Comment by sporksmith** [comment] 2020-05-28 21:36
I don't see much helpful in the logs unfortunately.

The next step is probably to try getting a stack trace for these segfaults. You'll need to run one of the affected tests under gdb (or generate a core file and try examining it under gdb). See https://github.com/shadow/shadow/blob/master/docs/5-Developer-Guide.md

**Comment by sakib570** [comment] 2020-05-29 07:38
Thanks a lot for your reply. I tried installing with Ubuntu 18.04.1 LTS and it worked fine but fails in  Ubuntu 18.04.3 LTS. I don't know whether it might give any hints for the problem.

**Comment by sporksmith** [comment] 2020-05-29 19:11
@sakib570 ok, sorry we weren't able to work it out. Closing since we can't reproduce, but feel free to reopen if you want to revisit and can get us a stack trace.

**Closed by sporksmith** 2020-05-29 19:11 UTC
