### ISSUE TITLE
Shadow doesn't build with libclang-dev from clang 19

### ISSUE THREAD

**Issue by datacompboy** [shadow/shadow#3372] opened 2024-07-23 15:42 UTC
**Describe the issue**
Can't build shadow using latest libclang-dev:

**To Reproduce**
```
apt purge ~nclang
apt install libclang-19-dev
./setup build --clean
```
Gives:
```
error[E0425]: cannot find value `syscallhandler_pwritev` in module `c`
   --> main/host/syscall/handler/uio.rs:366:56
    |
366 |                         return Self::legacy_syscall(c::syscallhandler_pwritev, ctx)
    |                                                        ^^^^^^^^^^^^^^^^^^^^^^ not found in `c`

error[E0425]: cannot find value `syscallhandler_pwritev2` in module `c`
   --> main/host/syscall/handler/uio.rs:435:56
    |
435 |                         return Self::legacy_syscall(c::syscallhandler_pwritev2, ctx)
    |                                                        ^^^^^^^^^^^^^^^^^^^^^^^ not found in `c`
```
(and many more errors).

Installation of versions 15 (latest in ubuntu jammy repo) or 18 (previous from llvm) fixes build.

```
apt purge ~nclang
apt install libclang-15-dev
./setup build --clean
#  => OK
apt purge ~nclang
apt install libclang-18-dev
./setup build --clean
#  => OK
```

**Operating System (please complete the following information):**
Ubuntu jammy

**Shadow (please complete the following information):**
Shadow 3.2.0, commit 217887cd2fc506b550f10a98786d79e921fb1449

**Comment by stevenengler** [comment] 2024-07-23 19:30
Where does the libclang-19-dev package come from on ubuntu 22.04? It doesn't seem to be in the ubuntu package repo: https://packages.ubuntu.com/search?suite=jammy&searchon=names&keywords=libclang

I also don't see libclang-19-dev on ubuntu 24.04: https://packages.ubuntu.com/search?suite=noble&searchon=names&keywords=libclang

**Comment by stevenengler** [comment] 2024-07-23 19:39
I see it's probably from one of llvm's own apt repos (https://apt.llvm.org/), but can you say which repo you specifically added since clang/llvm 19 isn't released yet.

Also I feel like this is a bindgen issue that they will probably fix once clang 19 is released, and there's probably not much we can do here for now other than update the bindgen/cbindgen dependencies. Maybe it's worth filing a bindgen issue, but it would be good to have exact steps to reproduce this issue in a container first.

**Comment by datacompboy** [comment] 2024-07-24 08:36
Correct, it's just what came after adding to sources.list line for
```
deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main
```
and just install clang then -- it installs 19 by default.

https://www.phoronix.com/news/LLVM-Clang-19-Feature-Freeze -- given Clang-19 was literally just branched, I don't understand why it is already default in the repo... :)


Anyway, that's the exact lib version it definitely fails with:
```
$ apt-cache policy libclang-19-dev
libclang-19-dev:
  Installed: (none)
  Candidate: 1:19~++20240722031324+65825cd5431c-1~exp1~20240722151445.1819
  Version table:
     1:19~++20240722031324+65825cd5431c-1~exp1~20240722151445.1819 500
        500 http://apt.llvm.org/jammy llvm-toolchain-jammy/main amd64 Packages
```

I agree, it does looks like bindgen -- at least, it should fail at bindgen step, not produce empty/partial output... I can't right now file issue here as I am not familiar with it, so if you could create minimal repro it would be great. If not, I'll try to do it later this week; and as workaround, use clang <19 for now :)

**Comment by stevenengler** [comment] 2024-12-29 00:21
This seems to build correctly for me, so I'm assuming it's been fixed somewhere and I'm going to close this.

Steps were roughly:

```
podman run -it ubuntu:24.04
wget https://apt.llvm.org/llvm-snapshot.gpg.key
mv llvm-snapshot.gpg.key /etc/apt/sources.list.d/llvm-snapshot.gpg.key
# add /etc/apt/sources.list.d/llvm.sources
apt update
apt-get install clang-19 libclang-19-dev
apt-get install -y cmake findutils libc-dbg libglib2.0-0 libglib2.0-dev make netbase python3 python3-networkx xz-utils util-linux
# install rust, git clone shadow, etc
CXX=clang++-19 ./setup build --clean
```

`/etc/apt/sources.list.d/llvm.sources`:

```text
Types: deb
URIs: http://apt.llvm.org/noble/
Suites: llvm-toolchain-noble-19
Components: main
Signed-by: /etc/apt/sources.list.d/llvm-snapshot.gpg.key
```

The build completes successfully.

**Closed by stevenengler** 2024-12-29 00:21 UTC
